name: plant_health_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  meta: ^1.9.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  lints: ^2.0.1
  test: ^1.19.2

